{
 "title": "Blockops Polkadot",
 "description": "A dashboard for monitoring Substrate based chains",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "chain", "label": "chain", "query": { "query": "label_values(chain)" } },
   { "name": "environment", "query": { "query": "label_values(environment)" } },
   { "name": "projectidentity", "query": { "query": "label_values(projectidentity)" } }
  ]
 },
 "panels": [
  {
   "title": "Height of the chain",
   "type": "stat",
   "gridPos": { "h": 6, "w": 15, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "substrate_block_height{chain=\"$chain\", environment=\"environment_id\",projectidentity=\"project_identity\"}",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Node uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - substrate_process_start_time_seconds{chain=\"$chain\",environment=\"environment_id\", projectidentity=\"project_identity\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Total No of incoming connections on the listening sockets",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "substrate_sub_libp2p_incoming_connections_total{chain=\"$chain\",environment=\"environment_id\",projectidentity=\"project_identity\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Diff -> ( Best Block - Finalized )",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "scalar(substrate_block_height{status=\"best\", chain=\"$chain\",environment=\"environment_id\",projectidentity=\"project_identity\"})-scalar(substrate_block_height{status=\"finalized\", chain=\"$chain\",environment=\"environment_id\",projectidentity=\"project_identity\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Peers connected, discovered, and requested",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "substrate_sub_libp2p_peers_count{chain=\"$chain\",environment=\"environment_id\",projectidentity=\"project_identity\"}",
     "legendFormat": "Peers count"
    },
    {
     "expr": "polkadot_sub_libp2p_peerset_num_discovered",
     "legendFormat": "Discovered peers"
    },
    {
     "expr": "polkadot_sub_libp2p_peerset_num_requested",
     "legendFormat": "Requested peers"
    }
   ]
  },
  {
   "title": "No of http RPC requests processed by chain (5m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(substrate_rpc_requests_finished{chain=\"$chain\", protocol=\"http\",environment=\"environment_id\",projectidentity=\"project_identity\"}[5m])",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "Tasks rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(substrate_tasks_polling_duration_bucket{chain=\"$chain\",environment=\"environment_id\",projectidentity=\"project_identity\"}[5m])",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Number of connected peers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "substrate_sub_libp2p_peers_count{chain=\"$chain\",environment=\"environment_id\",projectidentity=\"project_identity\"}",
     "legendFormat": "{{chain}}"
    }
   ]
  },
  {
   "title": "Running Tasks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(substrate_tasks_polling_started_total{chain=\"$chain\",environment=\"environment_id\",projectidentity=\"project_identity\"}[5m]) - rate(substrate_tasks_polling_duration_count{chain=\"$chain\",environment=\"environment_id\",projectidentity=\"project_identity\"}[5m])",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Connected peers",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "substrate_sync_peers{chain=\"$chain\",environment=\"environment_id\",projectidentity=\"project_identity\"}"
    }
   ]
  }
 ]
}